file = open("example.txt", "w+")
file.write("Hello Python Programming")
file.flush()   
file.seek(0)
print("Current file position:", file.tell())
data = file.read(5)
print("First 5 characters:", data)
print("Position after reading:", file.tell())
file.seek(6)
print("Position after seek(6):", file.tell())
print("Remaining text:", file.read())
file.close()