file = open("sample.txt", "w")
file.write("Hello Python\n")
file.write("Welcome to File Handling\n")
file.close()
file = open("sample.txt", "a")
lines = ["This is line 3\n", "This is line 4\n"]
file.writelines(lines)
file.close()
file = open("sample.txt", "r")
print("Using read():")
print(file.read())
file.close()
file = open("sample.txt", "r")
print("Using readline():")
print(file.readline())
file.close()
file = open("sample.txt", "r")
print("Using readlines():")
print(file.readlines())
file.close()