import pandas as pd
data = {'Name': ['A', 'B', 'C', 'D', 'E'],'Marks': [85, 92, 78, 90, 88]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
sorted_df = df.sort_values(by='Marks')
print("Sorted by Marks (Ascending):")
print(sorted_df)
sorted_df_desc = df.sort_values(by='Marks', ascending=False)
print("Sorted by Marks (Descending):")
print(sorted_df_desc)
print("First 3 rows:")
print(df[:3])
print("Rows from index 1 to 3:")
print(df[1:4])
print("Using loc (index 1 to 3):")
print(df.loc[1:3])
print("Using iloc (index 1 to 3):")
print(df.iloc[1:4])